spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/BlocAlert
  cloud:
    stream:
      bindings:
        consumePrice-out-0:
          destination: crypto.price
      kafka:
        binder:
          brokers: ${KAFKA_BROKERS}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 10
          min-idle: 1
          max-idle: 5

coingecko:
  url: ${COINGECKO_URL}
  secret: ${COINGECKO_SECRET}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, info
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    health:
      show-details: always